In [1]:
import numpy as np
import pandas as pd

In [3]:
Agric_df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "latin-1")

In [5]:
Agric_df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [23]:
Agric_df.sample(20)

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
36121,137,Mauritius,2511,Wheat and products,5301,Domestic supply quantity,1000 tonnes,141.00,145.00,129.00,145.00,149.00
22015,75,Gambia,2911,Pulses,664,Food supply (kcal/capita/day),kcal/capita/day,10.00,10.00,10.00,9.00,8.00
7490,35,Cabo Verde,2616,Plantains,5511,Production,1000 tonnes,NaN,NaN,0.00,NaN,NaN
9320,32,Cameroon,2781,"Fish, Body Oil",5521,Feed,1000 tonnes,0.00,0.00,0.00,0.00,0.00
59506,251,Zambia,2769,"Aquatic Animals, Others",5154,Other uses (non-food),1000 tonnes,0.00,0.00,0.00,0.00,0.00
28086,114,Kenya,2946,Animal fats,684,Fat supply quantity (g/capita/day),g/capita/day,1.85,1.65,1.70,1.54,1.65
20105,238,Ethiopia,2659,"Alcohol, Non-Food",5154,Other uses (non-food),1000 tonnes,0.00,0.00,NaN,NaN,0.00
58766,251,Zambia,2579,Sesameseed Oil,674,Protein supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
6740,233,Burkina Faso,2766,Cephalopods,664,Food supply (kcal/capita/day),kcal/capita/day,0.00,0.00,0.00,0.00,0.00
50335,202,South Africa,2570,"Oilcrops, Other",674,Protein supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
21016,74,Gabon,2577,Palm Oil,5911,Export Quantity,1000 tonnes,0.00,0.00,1.00,5.00,6.00
51436,276,Sudan,2908,Sugar Crops,5301,Domestic supply quantity,1000 tonnes,5808.00,5900.00,6000.00,5800.00,5800.00
28686,122,Lesotho,2555,Soyabeans,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
9781,37,Central African Republic,2909,Sugar & Sweeteners,5131,Processing,1000 tonnes,0.00,0.00,0.00,0.00,0.00
53653,217,Togo,2740,"Butter, Ghee",645,Food supply quantity (kg/capita/yr),kg,0.03,0.07,0.05,0.07,0.02
40198,144,Mozambique,2765,Crustaceans,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,0.00,0.00
59414,251,Zambia,2848,Milk - Excluding Butter,684,Fat supply quantity (g/capita/day),g/capita/day,0.91,0.94,0.73,0.88,0.96
9066,32,Cameroon,2640,Pepper,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
47889,195,Senegal,2614,"Citrus, Other",645,Food supply quantity (kg/capita/yr),kg,0.00,0.00,0.01,0.00,0.00
1052,4,Algeria,2736,"Offals, Edible",5142,Food,1000 tonnes,65.00,65.00,68.00,69.00,66.00

In [6]:
Agric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [7]:
Agric_df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [32]:
Agric_df.groupby(['Area']).nunique('Madagascar')

,Area Code,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,,,,
Algeria,1,119,116,17,17,5,409,410,403,400,409
Angola,1,121,118,18,18,5,378,364,367,366,367
Benin,1,119,116,17,17,5,364,346,346,361,370
Botswana,1,120,117,18,18,5,257,254,257,239,265
Burkina Faso,1,121,118,17,17,5,322,305,309,302,304
Cabo Verde,1,118,115,18,18,5,237,231,226,231,227
Cameroon,1,122,119,17,17,5,422,414,423,417,402
Central African Republic,1,119,116,17,17,5,242,231,227,245,234
Chad,1,122,119,17,17,5,284,280,274,281,275
Comoros,1,9,9,7,7,1,9,10,14,17,17
Congo,1,122,119,17,17,5,264,263,263,273,265
Côte d'Ivoire,1,122,119,17,17,5,377,383,390,380,393
Djibouti,1,117,114,17,17,5,214,210,213,210,212
Egypt,1,121,118,18,18,5,512,520,515,511,527
Eswatini,1,120,117,17,17,5,257,240,249,254,246
Ethiopia,1,122,119,17,17,5,407,401,395,391,398
Ethiopia PDR,1,7,7,8,8,1,1,1,1,1,1
Gabon,1,118,115,17,17,5,268,266,266,265,268
Gambia,1,114,111,17,17,5,225,223,230,226,227
Ghana,1,121,118,17,17,5,425,415,419,433,436
Guinea,1,121,118,17,17,5,326,317,326,322,334
Guinea-Bissau,1,115,112,17,17,5,226,224,232,224,226
Kenya,1,122,119,18,18,5,415,406,394,416,410
Lesotho,1,119,116,17,17,5,207,202,198,217,215
Liberia,1,119,116,17,17,5,233,233,227,230,229
Madagascar,1,122,119,17,17,5,323,317,330,333,325
Malawi,1,122,119,17,17,5,322,344,327,327,333
Mali,1,117,114,17,17,5,364,370,365,372,373
Mauritania,1,116,113,17,17,5,261,273,271,273,267
Mauritius,1,118,115,18,18,5,301,284,297,286,280
Morocco,1,121,118,17,17,5,467,451,460,444,458
Mozambique,1,122,119,17,17,5,352,352,352,356,348
Namibia,1,119,116,17,17,5,287,296,299,294,296
Niger,1,121,118,17,17,5,300,296,296,288,298
Nigeria,1,122,119,17,17,5,494,491,482,481,478
Rwanda,1,122,119,17,17,5,301,291,294,304,296
Sao Tome and Principe,1,114,111,18,18,5,193,196,204,203,197
Senegal,1,122,119,17,17,5,337,335,337,348,358
Seychelles,1,11,11,8,8,1,27,30,31,30,30
Sierra Leone,1,116,113,17,17,5,293,269,266,279,272
South Africa,1,120,117,17,17,5,516,509,523,496,509
Sudan,1,121,118,17,17,5,372,371,370,359,365
Sudan (former),1,9,9,8,8,1,1,1,1,1,1
Togo,1,118,115,17,17,5,287,295,298,299,314
Tunisia,1,120,117,17,17,5,382,392,387,390,387
Uganda,1,122,119,17,17,5,354,359,366,366,365
United Republic of Tanzania,1,122,119,17,17,5,465,457,443,434,435
Zambia,1,122,119,17,17,5,299,306,296,299,305
Zimbabwe,1,121,118,17,17,5,309,296,291,299,306

In [26]:
Agric_df.groupby(['Element']).max()

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,276,Zimbabwe,2961,Yams,5301,1000 tonnes,108756.00,110798.00,116483.00,112625.00,117038.00
Export Quantity,276,Zimbabwe,2961,Yams,5911,1000 tonnes,39686.00,52578.00,35420.00,34641.00,34641.00
Fat supply quantity (g/capita/day),276,Zimbabwe,2961,Yams,684,g/capita/day,93.73,96.79,94.33,97.13,94.94
Feed,276,Zimbabwe,2960,Yams,5521,1000 tonnes,29797.00,30472.00,31607.00,29580.00,31567.00
Food,276,Zimbabwe,2961,Yams,5142,1000 tonnes,49014.00,50705.00,52612.00,51220.00,54077.00
Food supply (kcal/capita/day),276,Zimbabwe,2961,Yams,664,kcal/capita/day,3435.00,3454.00,3451.00,3457.00,3450.00
Food supply quantity (kg/capita/yr),276,Zimbabwe,2961,Yams,645,kg,428.27,418.21,419.48,433.38,443.56
Import Quantity,276,Zimbabwe,2961,Yams,5611,1000 tonnes,19582.00,18824.00,19858.00,18627.00,18036.00
Losses,276,Zimbabwe,2949,Yams,5123,1000 tonnes,9807.00,9999.00,10432.00,10342.00,10355.00
Other uses (non-food),276,Zimbabwe,2961,Yams,5154,1000 tonnes,12552.00,6001.00,6099.00,17219.00,17221.00
Processing,276,Zimbabwe,2948,Wine,5131,1000 tonnes,18383.00,21609.00,21739.00,22174.00,22609.00
Production,276,Zimbabwe,2961,Yams,5511,1000 tonnes,109593.00,111663.00,119330.00,117702.00,118172.00
Protein supply quantity (g/capita/day),276,Zimbabwe,2961,Yams,674,g/capita/day,100.34,100.33,100.94,100.10,101.08
Residuals,276,Zimbabwe,2949,Yams,5170,1000 tonnes,16697.00,16136.00,18077.00,17476.00,17323.00
Seed,276,Zimbabwe,2960,Yams,5527,1000 tonnes,1258.00,1352.00,1402.00,1453.00,1474.00
Stock Variation,276,Zimbabwe,2961,Yams,5072,1000 tonnes,4569.00,3418.00,3266.00,5089.00,2226.00
Total Population - Both sexes,276,Zimbabwe,2501,Population,511,1000 persons,176405.00,181137.00,185960.00,190873.00,195875.00
Tourist consumption,193,Sao Tome and Principe,2949,Yams,5171,1000 tonnes,62.00,48.00,6.00,6.00,6.00

In [35]:
Agric_df.isna().count()

Area Code       60943
Area            60943
Item Code       60943
Item            60943
Element Code    60943
Element         60943
Unit            60943
Y2014           60943
Y2015           60943
Y2016           60943
Y2017           60943
Y2018           60943
dtype: int64

In [37]:
Agric_df.groupby(['Area']).min()

,Area Code,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,,,,
Algeria,4,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-39.0,-19.0,-63.00,-81.0,-90.0
Angola,7,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,0.0,-114.0,-142.00,-250.0,-240.0
Benin,53,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-12.0,-161.0,-46.00,-125.0,-256.0
Botswana,20,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-20.0,-12.0,-25.00,-38.0,-35.0
Burkina Faso,233,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-374.0,-294.0,-53.00,-281.0,-77.0
Cabo Verde,35,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-9.0,-10.0,-13.00,-7.0,-16.0
Cameroon,32,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-49.0,-117.0,-62.00,-147.0,-175.0
Central African Republic,37,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-50.0,-35.0,-2.00,-1.0,-4.0
Chad,39,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-20.0,-121.0,-14.00,-37.0,-10.0
Comoros,45,2761,Cephalopods,5142,Domestic supply quantity,1000 tonnes,0.0,0.0,0.00,0.0,0.0
Congo,46,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-7.0,-2.0,-4.00,-4.0,-17.0
Côte d'Ivoire,107,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-116.0,-208.0,-179.00,-244.0,-151.0
Djibouti,72,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-6.0,-4.0,-7.00,-2.0,-10.0
Egypt,59,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-288.0,-574.0,-985.00,-1582.0,-3396.0
Eswatini,209,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-11.0,-39.0,-51.00,-100.0,-10.0
Ethiopia,238,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-397.0,-549.0,-94.00,-792.0,-1000.0
Ethiopia PDR,62,2761,Crustaceans,5072,Domestic supply quantity,1000 tonnes,0.0,0.0,0.00,0.0,0.0
Gabon,74,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-29.0,-2.0,-18.00,-37.0,-22.0
Gambia,75,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-72.0,-30.0,-16.00,-2.0,-4.0
Ghana,81,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-324.0,-70.0,-162.00,-121.0,-502.0
Guinea,90,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-88.0,-186.0,-84.00,-108.0,-12.0
Guinea-Bissau,175,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-31.0,-6.0,-3.00,-3.0,-3.0
Kenya,114,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-623.0,-250.0,-703.00,-186.0,-177.0
Lesotho,122,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-6.0,-7.0,-5.00,-4.0,-70.0
Liberia,123,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-5.0,-9.0,-2.00,-19.0,-23.0
Madagascar,129,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-300.0,-305.0,-318.00,-324.0,-336.0
Malawi,130,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-344.0,-271.0,-374.00,-50.0,-237.0
Mali,133,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-849.0,-559.0,-560.00,-600.0,-598.0
Mauritania,136,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-7.0,-3.0,-34.00,-1.0,-12.0
Mauritius,137,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-42.0,-47.0,-22.00,-25.0,-34.0
Morocco,143,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-685.0,-179.0,-3225.00,-229.0,-169.0
Mozambique,144,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-219.0,-184.0,-108.00,-1200.0,-1445.0
Namibia,147,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-2.0,-4.0,-38.29,-35.0,-30.0
Niger,158,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-47.0,-57.0,-230.00,-682.0,-434.0
Nigeria,159,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-1796.0,-517.0,-399.00,-694.0,-374.0
Rwanda,184,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-838.0,-827.0,-679.00,-631.0,-682.0
Sao Tome and Principe,193,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-2.0,0.0,0.00,0.0,-1.0
Senegal,195,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-135.0,-33.0,-133.00,-68.0,-101.0
Seychelles,196,2761,"Aquatic Animals, Others",5072,Domestic supply quantity,1000 tonnes,0.0,-1.3,-0.28,0.0,0.0
Sierra Leone,197,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-46.0,-173.0,-240.00,-180.0,-180.0
South Africa,202,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-296.0,-3161.0,-1499.00,-144.0,-597.0
Sudan,276,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-147.0,-1284.0,-58.00,-819.0,-99.0
Sudan (former),206,2761,Aquatic Plants,5072,Domestic supply quantity,1000 tonnes,0.0,0.0,0.00,0.0,0.0
Togo,217,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-27.0,-42.0,-23.00,-32.0,-84.0
Tunisia,222,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-379.0,-154.0,-118.00,-186.0,-319.0
Uganda,226,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-208.0,-131.0,-239.00,-180.0,-271.0
United Republic of Tanzania,215,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-166.0,-317.0,-212.00,-865.0,-913.0
Zambia,251,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-67.0,-907.0,-506.00,-42.0,-529.0
Zimbabwe,181,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-119.0,-369.0,-417.00,-521.0,-273.0

In [17]:
Agric_df.nunique()

Area Code         49
Area              49
Item Code        122
Item             119
Element Code      18
Element           18
Unit               5
Y2014           4493
Y2015           4520
Y2016           4520
Y2017           4537
Y2018           4591
dtype: int64

In [19]:
Agric_df.shape

(60943, 12)

In [20]:
len(Agric_df)

60943